import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import StrategyTab from "@/components/StrategyTab";
import { UploadQueueProvider } from "@/contexts/UploadQueueContext";

const notoSansHeading = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        nunitoSans.variable,
        notoSansHeading.variable,
      )}
    >
      <body className="flex min-h-screen flex-col gap-8 pb-16">
        {/* One shared concurrency queue across all three strategy pages, so
            navigating between them doesn't reset the in-flight upload limit. */}
        <UploadQueueProvider>
          <Navbar />
          <div className="mx-auto flex w-full max-w-7xl flex-col gap-8">
            <StrategyTab />
            {children}
          </div>
        </UploadQueueProvider>
      </body>
    </html>
  );
}
